### ISSUE TITLE
ov7670

### ISSUE THREAD

**Issue by amirjak** [maximemoreillon/esp32_camera_streaming#1]
i want to use this code  for another project with ov7670 it's possible ?
![ov7670-camera-module-arduino-littlecraft-1704-24-littlecraft@11](https://user-images.githubusercontent.com/46311349/56453964-0812bf00-635f-11e9-8124-6c4e974d2ee0.jpg)

**Comment by maximemoreillon** [comment]
Sorry for the late reply. Unfortunately, this sketch is made specifically for the AI-thinker ESP32-CAM board so I cannot ensure support for other hardware.
